server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;

    location /mono-repo/ {
        try_files $uri $uri/ /mono-repo/index.html;
    }

    location = / {
        return 302 /mono-repo/;
    }
}
