export const sceneConfig = {
  backgroundColor: 0x010308,
  fogDensity: 0.0,
  environmentIntensity: 0.0,
  enableBloom: true,
  bloomStrength: 0.42,
  bloomRadius: 0.36,
  bloomThreshold: 0.22,
  enableChromaticAberration: true,
  aberration: 0.0024,
  vignetteAmt: 0.28,
  vignetteSmooth: 0.42,
  grainStrength: 0.006,
  enableDust: false,
  enableStars: true,
  enableOrbitControls: false,
  autoRotate: false,
  enableHoverEffect: true,
  enableGrid: false,
  monoliths: [
    {
      id: 'curso-01', label: 'HTML & CSS Foundations',
      model: 'Crystal_01.glb', colorA: 0x82d4ff, colorB: 0xff7ec7,
      x: -5.0, y: 0.8, z: -5.5, scale: 1.2,
      description: 'Domine os fundamentos da web — estrutura semântica, layouts responsivos e a arte do CSS moderno.',
      nextLesson: 'Flexbox — Dominando o Eixo Principal',
      progress: 72,
      skills: [{ name: 'HTML', pct: 89 }, { name: 'CSS', pct: 56 }, { name: 'Responsividade', pct: 41 }, { name: 'Acessibilidade', pct: 28 }],
      badge: { icon: '⬡', name: 'Arquiteto da Web', unlocked: true, color: '#82d4ff' },
    },
    {
      id: 'curso-02', label: 'JavaScript Profundo',
      model: 'Crystal_02.glb', colorA: 0x8cf2ff, colorB: 0x7a6cff,
      x: -3.0, y: -0.3, z: -4.0, scale: 0.9,
      description: 'Mergulhe nas entranhas do JS — closures, prototypes, event loop, async/await e muito além.',
      nextLesson: 'Promises e o Event Loop',
      progress: 38,
      skills: [{ name: 'ES6+', pct: 62 }, { name: 'Async', pct: 35 }, { name: 'DOM API', pct: 74 }, { name: 'Módulos', pct: 20 }],
      badge: { icon: '◈', name: 'Feiticeiro do Runtime', unlocked: false, color: '#7a6cff' },
    },
    {
      id: 'curso-03', label: 'React & Ecosistema',
      model: 'Crystal_03.glb', colorA: 0xff8cff, colorB: 0x5bc8ff,
      x: -1.0, y: 0.6, z: -6.0, scale: 1.1,
      description: 'Construa UIs reativas com React, Hooks, Context API e as principais bibliotecas do ecossistema.',
      nextLesson: 'useEffect — Efeitos Colaterais',
      progress: 55,
      skills: [{ name: 'Componentes', pct: 80 }, { name: 'Hooks', pct: 55 }, { name: 'Estado Global', pct: 40 }, { name: 'Performance', pct: 22 }],
      badge: { icon: '✦', name: 'Tecelão de Componentes', unlocked: false, color: '#ff8cff' },
    },
    {
      id: 'curso-04', label: 'Node.js & APIs',
      model: 'Crystal_01.glb', colorA: 0x9efaaa, colorB: 0x5a97ff,
      x: 1.0, y: -0.5, z: -4.5, scale: 0.95,
      description: 'Crie backends robustos com Node.js — REST APIs, autenticação, banco de dados e deploy.',
      nextLesson: 'Middleware Express Avançado',
      progress: 15,
      skills: [{ name: 'Node Core', pct: 30 }, { name: 'Express', pct: 42 }, { name: 'Banco de Dados', pct: 8 }, { name: 'Autenticação', pct: 5 }],
      badge: { icon: '⬟', name: 'Guardião do Servidor', unlocked: false, color: '#9efaaa' },
    },
    {
      id: 'curso-05', label: 'Design Systems',
      model: 'Crystal_02.glb', colorA: 0xffd37d, colorB: 0xff6dda,
      x: 3.0, y: 0.9, z: -5.8, scale: 1.3,
      description: 'Construa sistemas de design escaláveis — tokens, componentes atômicos e documentação viva.',
      nextLesson: 'Design Tokens na Prática',
      progress: 91,
      skills: [{ name: 'Tokens', pct: 95 }, { name: 'Storybook', pct: 88 }, { name: 'Figma', pct: 92 }, { name: 'Documentação', pct: 85 }],
      badge: { icon: '◉', name: 'Mestre do Pixel', unlocked: true, color: '#ffd37d' },
    },
    {
      id: 'curso-06', label: 'Three.js & WebGL',
      model: 'Crystal_03.glb', colorA: 0x72f1ff, colorB: 0x8f8fff,
      x: -2.0, y: 0.4, z: -7.0, scale: 1.0,
      description: 'Explore a fronteira da web 3D — renderização em tempo real, shaders GLSL e experiências imersivas.',
      nextLesson: 'Fragment Shaders: Cor e Luz',
      progress: 44,
      skills: [{ name: 'Scene Graph', pct: 68 }, { name: 'Materiais PBR', pct: 50 }, { name: 'Shaders GLSL', pct: 28 }, { name: 'Post-processing', pct: 44 }],
      badge: { icon: '⬡', name: 'Arquiteto Dimensional', unlocked: false, color: '#72f1ff' },
    },
    {
      id: 'curso-07', label: 'TypeScript Avançado',
      model: 'Crystal_01.glb', colorA: 0xd8b3ff, colorB: 0x5df2ff,
      x: 2.0, y: -0.1, z: -6.5, scale: 0.85,
      description: 'Domine o sistema de tipos do TypeScript — generics, utility types, decorators e inferência avançada.',
      nextLesson: 'Generics e Tipos Condicionais',
      progress: 29,
      skills: [{ name: 'Tipos Básicos', pct: 75 }, { name: 'Generics', pct: 30 }, { name: 'Decorators', pct: 12 }, { name: 'Inferência', pct: 25 }],
      badge: { icon: '◈', name: 'Oráculo dos Tipos', unlocked: false, color: '#d8b3ff' },
    },
    {
      id: 'curso-08', label: 'DevOps & Deploy',
      model: 'Crystal_02.glb', colorA: 0xffa88a, colorB: 0x78d4ff,
      x: 4.5, y: 0.2, z: -5.0, scale: 1.15,
      description: 'Automatize pipelines CI/CD, containerize com Docker e escale suas aplicações na nuvem.',
      nextLesson: 'Docker Compose na Prática',
      progress: 7,
      skills: [{ name: 'Docker', pct: 18 }, { name: 'CI/CD', pct: 8 }, { name: 'Cloud', pct: 5 }, { name: 'Monitoramento', pct: 3 }],
      badge: { icon: '✦', name: 'Senhor das Nuvens', unlocked: false, color: '#ffa88a' },
    },
  ],
  monolithHeight: 3.8,
  monolithRadius: 1.1,
  monolithBaseRoughness: 0.28,
  monolithTransmission: 0.42,
  pointLightIntensity: 1.85,
  accentLightIntensity: 1.1,
};
