BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

ALTER TABLE public.clinics ADD COLUMN IF NOT EXISTS plan_id TEXT;
ALTER TABLE public.clinics ADD COLUMN IF NOT EXISTS trial_used BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE public.clinics DROP CONSTRAINT IF EXISTS clinics_admin_email_key;
ALTER TABLE public.clinics DROP CONSTRAINT IF EXISTS clinics_plan_id_check;
ALTER TABLE public.clinics ADD CONSTRAINT clinics_plan_id_check CHECK (plan_id IS NULL OR plan_id IN ('essential', 'pro', 'elite'));
ALTER TABLE public.clinic_invitations ADD COLUMN IF NOT EXISTS psychologist_id INTEGER REFERENCES public.psychologists(id) ON DELETE SET NULL;

CREATE TABLE IF NOT EXISTS public.stripe_webhook_events (
  event_id TEXT PRIMARY KEY,
  event_type TEXT NOT NULL,
  processed_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.morpheus_audit_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  clinic_id UUID,
  table_name TEXT NOT NULL,
  operation TEXT NOT NULL,
  record_id TEXT,
  old_data JSONB,
  new_data JSONB,
  actor_id UUID DEFAULT auth.uid(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_clinic_doctors_user_clinic ON public.clinic_doctors (user_id, clinic_id);
CREATE INDEX IF NOT EXISTS idx_rooms_clinic ON public.rooms (clinic_id, id);
CREATE INDEX IF NOT EXISTS idx_psychologists_clinic ON public.psychologists (clinic_id, id);
CREATE INDEX IF NOT EXISTS idx_reservations_clinic_date_room ON public.reservations (clinic_id, date, room_id, start_time);
CREATE INDEX IF NOT EXISTS idx_reservations_clinic_psych_date ON public.reservations (clinic_id, psych_id, date);
CREATE INDEX IF NOT EXISTS idx_invitations_email_open ON public.clinic_invitations (lower(email), accepted, expires_at);
CREATE INDEX IF NOT EXISTS idx_audit_clinic_created ON public.morpheus_audit_log (clinic_id, created_at DESC);

CREATE OR REPLACE FUNCTION public.is_clinic_member(target_clinic UUID)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.clinic_doctors
    WHERE clinic_id = target_clinic AND user_id = auth.uid()
  );
$$;

CREATE OR REPLACE FUNCTION public.is_clinic_admin(target_clinic UUID)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.clinic_doctors
    WHERE clinic_id = target_clinic AND user_id = auth.uid() AND role = 'admin'
  );
$$;

CREATE OR REPLACE FUNCTION public.clinic_billing_active(target_clinic UUID)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.clinics
    WHERE id = target_clinic
      AND (
        billing_enforced = false
        OR (
          stripe_status IN ('active', 'trialing')
          AND (current_period_end IS NULL OR current_period_end >= now())
        )
      )
  );
$$;

CREATE OR REPLACE FUNCTION public.morpheus_plan_limit(target_clinic UUID, limit_name TEXT)
RETURNS INTEGER
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT CASE COALESCE(plan_id, 'essential')
    WHEN 'elite' THEN CASE limit_name WHEN 'rooms' THEN 10 WHEN 'doctors' THEN 20 WHEN 'workspaces' THEN 5 ELSE 0 END
    WHEN 'pro' THEN CASE limit_name WHEN 'rooms' THEN 6 WHEN 'doctors' THEN 15 WHEN 'workspaces' THEN 3 ELSE 0 END
    ELSE CASE limit_name WHEN 'rooms' THEN 3 WHEN 'doctors' THEN 10 WHEN 'workspaces' THEN 1 ELSE 0 END
  END
  FROM public.clinics
  WHERE id = target_clinic;
$$;

CREATE OR REPLACE FUNCTION public.handle_morpheus_auth_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.users (id, email, password_hash, display_name)
  VALUES (
    NEW.id,
    lower(COALESCE(NEW.email, '')),
    '',
    COALESCE(NULLIF(NEW.raw_user_meta_data->>'display_name', ''), NULLIF(NEW.raw_user_meta_data->>'full_name', ''), split_part(COALESCE(NEW.email, 'usuario'), '@', 1))
  )
  ON CONFLICT (id) DO UPDATE SET
    email = EXCLUDED.email,
    display_name = COALESCE(NULLIF(public.users.display_name, ''), EXCLUDED.display_name),
    updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created_morpheus ON auth.users;
CREATE TRIGGER on_auth_user_created_morpheus
AFTER INSERT OR UPDATE OF email, raw_user_meta_data ON auth.users
FOR EACH ROW EXECUTE FUNCTION public.handle_morpheus_auth_user();

CREATE OR REPLACE FUNCTION public.create_morpheus_clinic(clinic_name TEXT)
RETURNS UUID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  new_id UUID;
  account_email TEXT;
  account_name TEXT;
  current_count INTEGER;
  workspace_limit INTEGER;
BEGIN
  IF auth.uid() IS NULL THEN RAISE EXCEPTION 'authentication_required'; END IF;
  IF length(trim(clinic_name)) < 2 THEN RAISE EXCEPTION 'invalid_clinic_name'; END IF;

  SELECT email, display_name INTO account_email, account_name FROM public.users WHERE id = auth.uid();
  SELECT count(*) INTO current_count FROM public.clinic_doctors WHERE user_id = auth.uid() AND role = 'admin';
  SELECT COALESCE(max(public.morpheus_plan_limit(clinic_id, 'workspaces')), 1)
    INTO workspace_limit
    FROM public.clinic_doctors
    WHERE user_id = auth.uid() AND role = 'admin';
  IF current_count >= workspace_limit THEN RAISE EXCEPTION 'workspace_plan_limit'; END IF;

  INSERT INTO public.clinics (name, admin_email, admin_password_hash, user_id, stripe_status, billing_enforced)
  VALUES (trim(clinic_name), account_email, '', auth.uid(), 'inactive', true)
  RETURNING id INTO new_id;

  INSERT INTO public.clinic_doctors (clinic_id, user_id, email, password_hash, display_name, role)
  VALUES (new_id, auth.uid(), account_email, '', COALESCE(account_name, trim(clinic_name)), 'admin');
  RETURN new_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.accept_morpheus_invitation(invitation_token TEXT)
RETURNS UUID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  invitation public.clinic_invitations%ROWTYPE;
  account_email TEXT;
  account_name TEXT;
BEGIN
  IF auth.uid() IS NULL THEN RAISE EXCEPTION 'authentication_required'; END IF;
  SELECT email, display_name INTO account_email, account_name FROM public.users WHERE id = auth.uid();
  SELECT * INTO invitation
  FROM public.clinic_invitations
  WHERE token = invitation_token AND accepted = false AND expires_at > now()
  FOR UPDATE;
  IF invitation.id IS NULL OR lower(invitation.email) <> lower(account_email) THEN RAISE EXCEPTION 'invalid_invitation'; END IF;

  INSERT INTO public.clinic_doctors (clinic_id, user_id, psychologist_id, email, password_hash, display_name, role)
  VALUES (invitation.clinic_id, auth.uid(), invitation.psychologist_id, account_email, '', account_name, invitation.role)
  ON CONFLICT (clinic_id, email) DO UPDATE SET user_id = auth.uid(), psychologist_id = EXCLUDED.psychologist_id, role = EXCLUDED.role;
  UPDATE public.clinic_invitations SET accepted = true WHERE id = invitation.id;
  RETURN invitation.clinic_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.invite_morpheus_doctor(target_clinic UUID, doctor_name TEXT, doctor_email TEXT)
RETURNS TABLE(psychologist_id INTEGER, invitation_token TEXT, linked BOOLEAN)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  account_id UUID;
  new_psychologist_id INTEGER;
  new_token TEXT;
  clean_email TEXT := lower(trim(doctor_email));
  clean_name TEXT := trim(doctor_name);
  initials_value TEXT;
BEGIN
  IF NOT public.is_clinic_admin(target_clinic) THEN RAISE EXCEPTION 'admin_required'; END IF;
  IF clean_name = '' OR clean_email !~ '^[^@[:space:]]+@[^@[:space:]]+\.[^@[:space:]]+$' THEN RAISE EXCEPTION 'invalid_doctor'; END IF;
  IF EXISTS (SELECT 1 FROM public.clinic_doctors WHERE clinic_id = target_clinic AND lower(email) = clean_email) THEN RAISE EXCEPTION 'doctor_already_member'; END IF;

  initials_value := upper(left(regexp_replace(clean_name, '^(dr|dra)\.?\s+', '', 'i'), 1));
  INSERT INTO public.psychologists (clinic_id, name, short_name, initials, email, hex, rgb, light_hex, light_rgb)
  VALUES (target_clinic, clean_name, regexp_replace(clean_name, '^(dr|dra)\.?\s+', '', 'i'), COALESCE(NULLIF(initials_value, ''), 'PS'), clean_email, '#8fae9b', '143,174,155', '#3f6b5b', '63,107,91')
  RETURNING id INTO new_psychologist_id;

  SELECT id INTO account_id FROM public.users WHERE lower(email) = clean_email;
  IF account_id IS NOT NULL THEN
    INSERT INTO public.clinic_doctors (clinic_id, user_id, psychologist_id, email, password_hash, display_name, role)
    VALUES (target_clinic, account_id, new_psychologist_id, clean_email, '', clean_name, 'doctor');
    RETURN QUERY SELECT new_psychologist_id, NULL::TEXT, true;
  ELSE
    INSERT INTO public.clinic_invitations (clinic_id, psychologist_id, email, role)
    VALUES (target_clinic, new_psychologist_id, clean_email, 'doctor')
    RETURNING token INTO new_token;
    RETURN QUERY SELECT new_psychologist_id, new_token, false;
  END IF;
END;
$$;

CREATE OR REPLACE FUNCTION public.get_morpheus_workspace_counts()
RETURNS TABLE(clinic_id UUID, room_count BIGINT, doctor_count BIGINT)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT membership.clinic_id,
    (SELECT count(*) FROM public.rooms room WHERE room.clinic_id = membership.clinic_id),
    (SELECT count(*) FROM public.psychologists psychologist WHERE psychologist.clinic_id = membership.clinic_id)
  FROM public.clinic_doctors membership
  WHERE membership.user_id = auth.uid();
$$;

CREATE OR REPLACE FUNCTION public.enforce_morpheus_entity_limits()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public
AS $$
DECLARE current_count INTEGER;
BEGIN
  IF TG_TABLE_NAME = 'rooms' THEN
    SELECT count(*) INTO current_count FROM public.rooms WHERE clinic_id = NEW.clinic_id;
    IF current_count >= public.morpheus_plan_limit(NEW.clinic_id, 'rooms') THEN RAISE EXCEPTION 'room_plan_limit'; END IF;
  ELSIF TG_TABLE_NAME = 'psychologists' THEN
    SELECT count(*) INTO current_count FROM public.psychologists WHERE clinic_id = NEW.clinic_id;
    IF current_count >= public.morpheus_plan_limit(NEW.clinic_id, 'doctors') THEN RAISE EXCEPTION 'doctor_plan_limit'; END IF;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS rooms_plan_limit ON public.rooms;
CREATE TRIGGER rooms_plan_limit BEFORE INSERT ON public.rooms FOR EACH ROW EXECUTE FUNCTION public.enforce_morpheus_entity_limits();
DROP TRIGGER IF EXISTS psychologists_plan_limit ON public.psychologists;
CREATE TRIGGER psychologists_plan_limit BEFORE INSERT ON public.psychologists FOR EACH ROW EXECUTE FUNCTION public.enforce_morpheus_entity_limits();

CREATE OR REPLACE FUNCTION public.prevent_morpheus_reservation_conflict()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public
AS $$
BEGIN
  IF NEW.start_time !~ '^([01][0-9]|2[0-3]):[0-5][0-9]$'
     OR NEW.end_time !~ '^([01][0-9]|2[0-3]):[0-5][0-9]$'
     OR NEW.start_time >= NEW.end_time THEN
    RAISE EXCEPTION 'invalid_reservation_time';
  END IF;
  PERFORM pg_advisory_xact_lock(hashtext(NEW.clinic_id::text || ':' || NEW.room_id::text || ':' || NEW.date::text));
  IF EXISTS (
    SELECT 1 FROM public.reservations
    WHERE clinic_id = NEW.clinic_id AND room_id = NEW.room_id AND date = NEW.date
      AND id <> COALESCE(NEW.id, '')
      AND NEW.start_time < end_time AND NEW.end_time > start_time
  ) THEN RAISE EXCEPTION 'reservation_conflict'; END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS reservations_prevent_conflict ON public.reservations;
CREATE TRIGGER reservations_prevent_conflict BEFORE INSERT OR UPDATE ON public.reservations
FOR EACH ROW EXECUTE FUNCTION public.prevent_morpheus_reservation_conflict();

CREATE OR REPLACE FUNCTION public.audit_morpheus_change()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE source JSONB; target_clinic UUID; target_id TEXT;
BEGIN
  source := CASE WHEN TG_OP = 'DELETE' THEN to_jsonb(OLD) ELSE to_jsonb(NEW) END;
  target_clinic := NULLIF(source->>'clinic_id', '')::uuid;
  target_id := source->>'id';
  INSERT INTO public.morpheus_audit_log (clinic_id, table_name, operation, record_id, old_data, new_data)
  VALUES (target_clinic, TG_TABLE_NAME, TG_OP, target_id, CASE WHEN TG_OP IN ('UPDATE', 'DELETE') THEN to_jsonb(OLD) END, CASE WHEN TG_OP IN ('INSERT', 'UPDATE') THEN to_jsonb(NEW) END);
  RETURN CASE WHEN TG_OP = 'DELETE' THEN OLD ELSE NEW END;
END;
$$;

DROP TRIGGER IF EXISTS rooms_audit ON public.rooms;
CREATE TRIGGER rooms_audit AFTER INSERT OR UPDATE OR DELETE ON public.rooms FOR EACH ROW EXECUTE FUNCTION public.audit_morpheus_change();
DROP TRIGGER IF EXISTS psychologists_audit ON public.psychologists;
CREATE TRIGGER psychologists_audit AFTER INSERT OR UPDATE OR DELETE ON public.psychologists FOR EACH ROW EXECUTE FUNCTION public.audit_morpheus_change();
DROP TRIGGER IF EXISTS reservations_audit ON public.reservations;
CREATE TRIGGER reservations_audit AFTER INSERT OR UPDATE OR DELETE ON public.reservations FOR EACH ROW EXECUTE FUNCTION public.audit_morpheus_change();

DO $$
DECLARE item RECORD;
BEGIN
  FOR item IN SELECT schemaname, tablename, policyname FROM pg_policies
    WHERE schemaname = 'public' AND tablename IN ('users', 'clinics', 'clinic_doctors', 'clinic_invitations', 'rooms', 'psychologists', 'reservations', 'admin_config', 'coupons', 'morpheus_audit_log', 'stripe_webhook_events')
  LOOP
    EXECUTE format('DROP POLICY IF EXISTS %I ON %I.%I', item.policyname, item.schemaname, item.tablename);
  END LOOP;
END $$;

ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.clinics ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.clinic_doctors ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.clinic_invitations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rooms ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.psychologists ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reservations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admin_config ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.coupons ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.morpheus_audit_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stripe_webhook_events ENABLE ROW LEVEL SECURITY;

CREATE POLICY users_own_select ON public.users FOR SELECT TO authenticated USING (id = auth.uid());
CREATE POLICY users_own_update ON public.users FOR UPDATE TO authenticated USING (id = auth.uid()) WITH CHECK (id = auth.uid());
CREATE POLICY clinics_member_select ON public.clinics FOR SELECT TO authenticated USING (public.is_clinic_member(id));
CREATE POLICY clinic_doctors_member_select ON public.clinic_doctors FOR SELECT TO authenticated USING (public.is_clinic_member(clinic_id));
CREATE POLICY clinic_doctors_admin_write ON public.clinic_doctors FOR ALL TO authenticated USING (public.is_clinic_admin(clinic_id)) WITH CHECK (public.is_clinic_admin(clinic_id));
CREATE POLICY invitations_admin_select ON public.clinic_invitations FOR SELECT TO authenticated USING (public.is_clinic_admin(clinic_id) OR lower(email) = lower(COALESCE(auth.jwt()->>'email', '')));
CREATE POLICY invitations_admin_insert ON public.clinic_invitations FOR INSERT TO authenticated WITH CHECK (public.is_clinic_admin(clinic_id));
CREATE POLICY invitations_admin_update ON public.clinic_invitations FOR UPDATE TO authenticated USING (public.is_clinic_admin(clinic_id)) WITH CHECK (public.is_clinic_admin(clinic_id));
CREATE POLICY invitations_admin_delete ON public.clinic_invitations FOR DELETE TO authenticated USING (public.is_clinic_admin(clinic_id));
CREATE POLICY rooms_member_select ON public.rooms FOR SELECT TO authenticated USING (public.is_clinic_member(clinic_id) AND public.clinic_billing_active(clinic_id));
CREATE POLICY rooms_admin_insert ON public.rooms FOR INSERT TO authenticated WITH CHECK (public.is_clinic_admin(clinic_id) AND public.clinic_billing_active(clinic_id));
CREATE POLICY rooms_admin_update ON public.rooms FOR UPDATE TO authenticated USING (public.is_clinic_admin(clinic_id) AND public.clinic_billing_active(clinic_id)) WITH CHECK (public.is_clinic_admin(clinic_id) AND public.clinic_billing_active(clinic_id));
CREATE POLICY rooms_admin_delete ON public.rooms FOR DELETE TO authenticated USING (public.is_clinic_admin(clinic_id) AND public.clinic_billing_active(clinic_id));
CREATE POLICY psychologists_member_select ON public.psychologists FOR SELECT TO authenticated USING (public.is_clinic_member(clinic_id) AND public.clinic_billing_active(clinic_id));
CREATE POLICY psychologists_admin_insert ON public.psychologists FOR INSERT TO authenticated WITH CHECK (public.is_clinic_admin(clinic_id) AND public.clinic_billing_active(clinic_id));
CREATE POLICY psychologists_admin_update ON public.psychologists FOR UPDATE TO authenticated USING (public.is_clinic_admin(clinic_id) AND public.clinic_billing_active(clinic_id)) WITH CHECK (public.is_clinic_admin(clinic_id) AND public.clinic_billing_active(clinic_id));
CREATE POLICY psychologists_admin_delete ON public.psychologists FOR DELETE TO authenticated USING (public.is_clinic_admin(clinic_id) AND public.clinic_billing_active(clinic_id));
CREATE POLICY reservations_member_select ON public.reservations FOR SELECT TO authenticated USING (public.is_clinic_member(clinic_id) AND public.clinic_billing_active(clinic_id));
CREATE POLICY reservations_member_insert ON public.reservations FOR INSERT TO authenticated WITH CHECK (public.clinic_billing_active(clinic_id) AND (public.is_clinic_admin(clinic_id) OR EXISTS (SELECT 1 FROM public.clinic_doctors cd WHERE cd.clinic_id = reservations.clinic_id AND cd.user_id = auth.uid() AND cd.psychologist_id = reservations.psych_id)));
CREATE POLICY reservations_admin_or_owner_update ON public.reservations FOR UPDATE TO authenticated USING (public.is_clinic_admin(clinic_id) OR EXISTS (SELECT 1 FROM public.clinic_doctors cd WHERE cd.clinic_id = reservations.clinic_id AND cd.user_id = auth.uid() AND cd.psychologist_id = reservations.psych_id)) WITH CHECK (public.clinic_billing_active(clinic_id));
CREATE POLICY reservations_admin_or_owner_delete ON public.reservations FOR DELETE TO authenticated USING (public.is_clinic_admin(clinic_id) OR EXISTS (SELECT 1 FROM public.clinic_doctors cd WHERE cd.clinic_id = reservations.clinic_id AND cd.user_id = auth.uid() AND cd.psychologist_id = reservations.psych_id));
CREATE POLICY audit_admin_select ON public.morpheus_audit_log FOR SELECT TO authenticated USING (public.is_clinic_admin(clinic_id));
CREATE POLICY coupons_active_read ON public.coupons FOR SELECT USING (active = true AND valid_from <= now() AND (valid_until IS NULL OR valid_until >= now()));

GRANT EXECUTE ON FUNCTION public.create_morpheus_clinic(TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.accept_morpheus_invitation(TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.invite_morpheus_doctor(UUID, TEXT, TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_morpheus_workspace_counts() TO authenticated;
REVOKE ALL ON public.stripe_webhook_events FROM anon, authenticated;
REVOKE INSERT, UPDATE, DELETE ON public.morpheus_audit_log FROM anon, authenticated;

INSERT INTO public.coupons (code, label, discount_pct, max_uses, valid_from, valid_until, active)
VALUES ('MORPHEUS99', 'Teste de pagamento 99% OFF', 99, 100, now(), now() + interval '6 months', true)
ON CONFLICT (code) DO UPDATE SET discount_pct = 99, active = true;

COMMIT;
